[package]
name = "rusty-bush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.6"
winit_input_helper = "0.14"
pixels = "0.13.0"
rand = "0.8.5"
serde_json = "1.0"